### ISSUE TITLE
Cannot GET /posts/

### ISSUE THREAD

**Issue by vikramrojo** [alexcarpenter/eleventy-boilerplate#1]
new to 11ty but liked the simpleness of this boilerplate. i keep getting `Cannot GET /posts/`. thanks.

**Comment by fschoenfeldt** [comment]
having the same issue by serving via `npm start`.

**Comment by alexcarpenter** [comment]
@atav1k @fschoenfeldt I've updated this to include a posts page. If you pull the latest from master you should be good to go! https://github.com/alexcarpenter/eleventy-boilerplate/commit/5f9466a0dab28f93a785d0114808df67de28a6f8
